### ISSUE TITLE
Resource registry registration is not working

### ISSUE THREAD

**Issue by hvelarde** [collective/example.p4p5#2]
I enabled Travis for this repo and added some tests to verify CSS and JS resources are being installed and uninstalled.

as you can see, both builds are failing.

**Comment by ebrehault** [comment]
Hi @hvelarde, thank you for setting up the tests :)

There are 2 problems here:
- testing.py must perform `applyProfile(portal, 'example.p4p5:plone{VERSION}')`, or the CSS and JS will not be declared
- on Plone 5, the test you wrote cannot work (see my comment in your PR)

I will try to fix that soon.

**Comment by hvelarde** [comment]
no, that will not work, because you will have to do the same manually when you install the package.

now you are starting to understand the issues behind your approach; I think you must conditionally register the resources so they are automatically applied in both, Plone 4 and 5.

@agitator has done some similar work for [sc.social.like](https://github.com/collective/sc.social.like/commits/plone5?author=agitator)

**Comment by ebrehault** [comment]
Fixed.
Have a look to my last commits.

**Comment by hvelarde** [comment]
no, is not fixed: tests are failing; do not remove uninstall tests, we need them:

https://travis-ci.org/collective/example.p4p5/builds/104092812

**Comment by ebrehault** [comment]
and also it looks like the test is not detecting the plone version properly when run in travis, I guess I made something wrong in the buildout

**Comment by ebrehault** [comment]
uninstall tests are back :)

It implied to create a `uninstall-plone5` profile, I need to document that in the README.
